/**
 * Image ids (04-§9.7–9.10, ADR 0015).
 *
 * An id is `img-` followed by the first twelve hexadecimal characters of SHA-256 over
 * the finished WebP file. Deriving it from the content means no counter has to be kept
 * anywhere: two pull requests can add an image each without colliding, and the same
 * photo added twice gets the same id instead of a second copy.
 *
 * The prefix is not decoration. Without it an id of nothing but digits — about three in
 * a thousand — would be read as an integer by YAML and lose its leading zeros.
 *
 * `imageIdFor` is how a *new* id is derived. Nothing re-hashes a file afterwards: the
 * QA placeholders are regenerated by sharp and would otherwise start failing whenever
 * the image library changes its output by a byte (04-§9.10).
 */
import { createHash } from "node:crypto";

export const IMAGE_ID_PREFIX = "img-";

/** How many hex characters follow the prefix. 48 bits: at 1500 images a collision is around 4 in a billion. */
const ID_LENGTH = 12;

/** 04-§9.7. Anchored, so it matches an id and not an id inside a longer string. */
export const IMAGE_ID_PATTERN = new RegExp(`^${IMAGE_ID_PREFIX}[0-9a-f]{${ID_LENGTH}}$`);

/** Human-readable form of the rule, for validator messages. Swedish, because editors read them. */
export const IMAGE_ID_DESCRIPTION = `"${IMAGE_ID_PREFIX}" och tolv tecken 0–9 och a–f, till exempel ${IMAGE_ID_PREFIX}a3f2c1d8b901`;

export function isImageId(value: unknown): value is string {
  return typeof value === "string" && IMAGE_ID_PATTERN.test(value);
}

/** The id for a finished WebP file's bytes. */
export function imageIdFor(data: Uint8Array): string {
  const digest = createHash("sha256").update(data).digest("hex");
  return `${IMAGE_ID_PREFIX}${digest.slice(0, ID_LENGTH)}`;
}

/** `img-a3f2c1d8b901` → `img-a3f2c1d8b901.webp`. The images directory is flat (04-§9.1). */
export function imageFileName(id: string): string {
  return `${id}.webp`;
}

/** The image post that describes `id`, relative to the dataset directory. */
export function imagePostFile(id: string): string {
  return `images/${id}.yaml`;
}
